### ISSUE TITLE
[bug] Abilities apply buffs too early

### ISSUE THREAD

**Issue by xiashtra** [xiv-gear-planner/gear-planner#42]
Currently, abilities that apply a buff activate that buff at the ability snapshot time, instead of the end of the ability cast.  This causes buffs to apply too early, and for abilities to snapshot their own buffs before they are finished casting.  This can be seen in the current RPR sim, where the initial use of Shadow of Death is benefitting from the Death's Design buff before the buff should be active.

ref: https://github.com/xiv-gear-planner/gear-planner/blob/530499cde768b96be91366f23ac8dd45dab30f46/src/scripts/sims/sim_processors.ts#L459-L462

https://github.com/xiv-gear-planner/gear-planner/blob/530499cde768b96be91366f23ac8dd45dab30f46/src/scripts/sims/sim_processors.ts#L502-L504

**Comment by xpdota** [comment]
I think fixing this *properly* is going to be more involved, since it would need to factor in application delay, which complicates matters for some classes. e.g. SCH since you have to intentionally delay ED if you use it immediately after chain - I'd have to add the concept of "try to delay this oGCD but don't clip the GCD". I think it might be good enough as a stopgap to fix the immediate issue to just make it apply when the animation lock finishes OR after the application delay, whichever is shorter.

**Comment by xiashtra** [comment]
My immediate concern is casted gcds that are applying their buffs 0.5s early (at the cast snapshot) and losing a significant amount of buff time due to that; moving the buff application to after the gcd animation lock is going to make them apply 0.1s too late (due to the caster tax) but that's less egregious, provided #43 is fixed so cast times are reduced properly.
